### ISSUE TITLE
Can we get rid of this?

### ISSUE THREAD

**Issue by daisyrocha** [halHalberstadt/Project02-Group07-CST438#59]
This block of code will return all data from the user, including user password, which I think we don't want. In the UserController file, line 16, Turi included a function that will return the similar data, but WITHOUT the user's password, which I think might be a better option to have.

Are we okay to delete this block?

https://github.com/halHalberstadt/Project02-Group07-CST438/blob/a6b968dcc8e7e51e99631d0566f429bfe1bf6e7a/src/main/java/com/example/group07/project2/UserApi.java#L30

**Comment by halHalberstadt** [comment]
I will modify that function to print like my get user function and then push it in like 15 min.
